# Site settings
# in the templates available like {{ site.myvariable }}.
title: Clean portfolio theme for Jekyll powered by Bootstrap 4.
email: oks153123@naver.com
brand: 오승열
headline: 26세
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://seung-yeol.github.io" # the base hostname & protocol for your site
copyright:

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: oks153123@naver.com

# Tracking
googleAnalitycsID: UA-83933844-1
